### ISSUE TITLE
Cannot build due to WorldGuardExtraFlags not on any maven used by the project

### ISSUE THREAD

**Issue by Justsnoopy30** [SpleefX/SpleefX#3]
Cannot build, see title.

**Comment by ReflxctionDev** [comment]
Yeah, unfortunately, WorldGuard ExtraFlags is not on any public repository. Therefore you have to build it manually in order to get it. 

To get it, download [WorldGuard ExtraFlags](https://www.spigotmc.org/resources/4823/download?version=326911) and follow the instructions in [this answer in StackOverflow](https://stackoverflow.com/a/4955695/10038867). Make sure you get the group ID, artifact ID and version correctly!

**Comment by Justsnoopy30** [comment]
Unfortunately, I cannot build WorldGuardExtraFlags as build fails due to this error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project
 wg: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]`

**Comment by Justsnoopy30** [comment]
Oh, I need to download the precompiled jar...

**Comment by ReflxctionDev** [comment]
Make sure you clone the rewrite branch by the way... `master` is no longer maintained. `rewrite` will soon be the default branch

**Comment by Justsnoopy30** [comment]
I have cloned the rewrite branch already. Now I am getting `Cannot expand ZIP 'C:\Users\~~~~~\SpleefX\1_16_R1\build\libs\1_16_R1-3.8.7-BETA-all.jar' as it does not exist`

**Comment by ReflxctionDev** [comment]
Run `gradle shadowJar` before running `gradle build`.

**Comment by Justsnoopy30** [comment]
Successfully built.
